#!/bin/bash

set -e
set -x

apt-get update
apt-get install -y \
  build-essential libsndfile-dev libmpg123-dev \
  python3 python3-venv ffmpeg \
  rabbitmq-server nginx

if [[ ! -d /opt/DynamicAudioNormalizer ]]; then
  WORK_DIR=`mktemp -d`
  pushd "$WORK_DIR"
  git clone https://github.com/lordmulder/DynamicAudioNormalizer.git
  cd DynamicAudioNormalizer
  make MODE=minimal
  cp -r "bin/`date +'%Y-%m-%d'`" /opt/DynamicAudioNormalizer
  popd
  rm -rf $WORK_DIR
fi

if ! getent passwd youtube-sync > /dev/null; then
  useradd --system --user-group --create-home \
    --shell /bin/bash \
    --home-dir /home/youtube-sync \
    youtube-sync
fi

if [[ ! -f /home/youtube-sync/.ssh/id_rsa.pub ]]; then
  sudo -u youtube-sync ssh-keygen \
    -t rsa -N '' \
    -f /home/youtube-sync/.ssh/id_rsa
  ssh-keyscan -H server.abhayagiri.org | sudo -u youtube-sync \
    tee -a /home/youtube-sync/.ssh/known_hosts
fi

if [[ ! -d /opt/youtube-sync ]]; then
  mkdir /opt/youtube-sync
  chown youtube-sync:youtube-sync /opt/youtube-sync
  sudo -u youtube-sync git clone \
    https://github.com/abhayagiri/youtube-sync.git /opt/youtube-sync
fi

cd /opt/youtube-sync

sudo -u youtube-sync git pull

if [[ ! -d venv ]]; then
  sudo -u youtube-sync python3 -m venv venv
fi

sudo -u youtube-sync venv/bin/pip install --upgrade pip setuptools wheel
sudo -u youtube-sync venv/bin/pip install --upgrade -r requirements.txt

if [[ ! -f instance/local.cfg ]]; then
  sudo -u youtube-sync ./app setup_local_cfg \
    --dan-bin="/opt/DynamicAudioNormalizer/DynamicAudioNormalizerCLI.bin" \
    --remote-host="server.abhayagiri.org" \
    --remote-user="abhayagiri" \
    --remote-path="www.abhayagiri.org/shared/public/media/audio/youtube"
fi

cp -f server/youtube-sync-gunicorn.service /etc/systemd/system
cp -f server/youtube-sync-celery.service /etc/systemd/system
systemctl daemon-reload
systemctl enable youtube-sync-gunicorn.service
systemctl enable youtube-sync-celery.service
systemctl restart youtube-sync-gunicorn.service
systemctl restart youtube-sync-celery.service

if [[ ! -d /root/.acme.sh ]]; then
  curl https://get.acme.sh | sh
fi

domain="youtube-sync.abhayagiri.org"
if [[ ! -d /etc/nginx/certs/$domain ]]; then
  mkdir -p /etc/nginx/certs/$domain
  chmod 700 /etc/nginx/certs/$domain
  /root/.acme.sh/acme.sh --issue -d $domain -w /var/www/html
  /root/.acme.sh/acme.sh --installcert -d $domain \
  --certpath /etc/nginx/certs/$domain/cert \
  --keypath /etc/nginx/certs/$domain/key \
  --fullchainpath /etc/nginx/certs/$domain/fullchain \
  --reloadcmd "systemctl reload nginx.service"
fi

cp -f server/youtube-sync.nginx-conf /etc/nginx/sites-available/youtube-sync
rm -f /etc/nginx/sites-enabled/default
ln -sf ../sites-available/youtube-sync /etc/nginx/sites-enabled/youtube-sync
systemctl restart nginx.service
